// src/components/shared/Header.tsx
'use client';

import { useHeaderService } from '@/src/hooks/useHeader';
import { useEffect, useRef } from 'react';

export default function Header() {
  const headerRef = useRef<HTMLElement>(null);
  const hamburgerRef = useRef<HTMLButtonElement>(null);
  const navMenuRef = useRef<HTMLElement>(null);

  const { navLinks, setActiveLink } = useHeaderService();

  useEffect(() => {
    const handleScroll = () => {
      if (headerRef.current) {
        if (window.scrollY > headerRef.current.offsetTop) {
          headerRef.current.classList.add('navbar-fixed');
        } else {
          headerRef.current.classList.remove('navbar-fixed');
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    const hamburger = hamburgerRef.current;
    const navMenu = navMenuRef.current;

    if (hamburger && navMenu) {
      const toggleMenu = () => {
        hamburger.classList.toggle('hamburger-active');
        navMenu.classList.toggle('hidden');
      };

      hamburger.addEventListener('click', toggleMenu);

      return () => {
        hamburger.removeEventListener('click', toggleMenu);
      };
    }
  }, []);

  return (
    <header
      ref={headerRef}
      className="bg-transparent absolute top-0 left-0 w-full flex items-center z-10"
    >
      <div className="container">
        <div className="flex items-center justify-between relative">
          <a
            href="#home"
            className="text-3xl lg:text-4xl font-medium block py-6"
            onClick={(e) => {
              e.preventDefault();
              setActiveLink('#home');
            }}
          >
            Ihsan
          </a>

          <div className="flex items-center">
            <button
              ref={hamburgerRef}
              type="button"
              className="block absolute right-4 lg:hidden cursor-pointer"
            >
              <span className="hamburger-line transition duration-300 ease-in-out origin-top-left"></span>
              <span className="hamburger-line transition duration-300 ease-in-out"></span>
              <span className="hamburger-line transition duration-300 ease-in-out origin-bottom-left"></span>
            </button>

            <nav
              ref={navMenuRef}
              className="hidden absolute py-5 bg-primary shadow-lg rounded-lg max-w-[250px] w-full right-4 top-full lg:block lg:static lg:bg-transparent lg:max-w-full lg:shadow-none lg:rounded-none"
            >
              <ul className="block px-8 lg:px-0 lg:flex lg:gap-12">
                {navLinks.map((link, index) => (
                  <li key={index} className="group relative">
                    <a
                      href={link.href}
                      onClick={(e) => {
                        e.preventDefault();
                        setActiveLink(link.href);
                      }}
                      className={`relative inline-block text-base py-2 transition-colors duration-300 ${
                        link.isActive ? 'text-accent' : 'text-white'
                      }`}
                    >
                      {link.name}
                      <span
                        className={`absolute left-0 -bottom-0.5 h-[2px] bg-accent transition-all duration-300
                          ${link.isActive ? 'w-full' : 'w-0 group-hover:w-full'}
                        `}
                      />
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </header>
  );
}

// src/app/components/shared/header/header.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  HostListener,
  inject,
  viewChild,
} from '@angular/core';
import { HeaderService } from './header.service';
import { NgClass } from '@angular/common';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [NgClass],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
})
export class HeaderComponent implements AfterViewInit {
  private headerService = inject(HeaderService);
  private headerRef = viewChild.required<ElementRef<HTMLElement>>('header');
  private navMenuRef = viewChild.required<ElementRef<HTMLElement>>('navMenu');
  private hamburgerRef = viewChild.required<ElementRef<HTMLButtonElement>>('hamburger');

  links = this.headerService.navLinks;

  @HostListener('window:scroll')
  onScroll() {
    if (window.scrollY > this.headerRef().nativeElement.offsetTop) {
      this.headerRef().nativeElement.classList.add('navbar-fixed');
    } else {
      this.headerRef().nativeElement.classList.remove('navbar-fixed');
    }
  }

  ngAfterViewInit(): void {
    this.hamburgerRef().nativeElement.addEventListener('click', () => {
      this.hamburgerRef().nativeElement.classList.toggle('hamburger-active');
      this.navMenuRef().nativeElement.classList.toggle('hidden');
    });
  }

  onConnectClicked(href: string): void {
    this.headerService.setActiveLink(href);
  }
}

<header class="bg-transparent absolute top-0 left-0 w-full flex items-center z-10" #header>
  <div class="container">
    <div class="flex items-center justify-between relative">
      <!-- Logo -->
      <a href="#home" class="text-4xl font-medium block py-6">Ihsan</a>

      <div class="flex items-center gap-8">
        <!-- Hamburger Button -->
        <button #hamburger type="button" class="block absolute right-4 lg:hidden">
          <span class="hamburger-line transition duration-300 ease-in-out origin-top-left"></span>
          <span class="hamburger-line transition duration-300 ease-in-out"></span>
          <span class="hamburger-line transition duration-300 ease-in-out origin-bottom-left"></span>
        </button>

        <!-- Navigation Menu -->
        <nav
          class="hidden absolute py-5 bg-primary shadow-lg rounded-lg max-w-[250px] w-full right-4 top-full lg:block lg:static lg:bg-transparent lg:max-w-full lg:shadow-none lg:rounded-none"
          #navMenu>
          <ul class="block px-8 lg:flex lg:gap-12">
            @for (link of links(); track $index) {
            <li class="group">
              <a [href]="link.href" class="text-base py-2 flex group-hover:text-accent"
                [ngClass]="{ 'text-accent lg:border-b-2 lg:border-accent w-min': link.isActive }"
                (click)="onConnectClicked(link.href)">
                {{ link.name }}
              </a>
            </li>
            }
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>
