// src/components/resume/ContentCard.tsx
import { ResumeData } from '@/src/types/resume';

interface Props {
  data: ResumeData;
}

export default function ContentCard({ data }: Props) {
  return (
    <div className="p-8 bg-secondary rounded-lg">
      <div className="flex flex-col gap-4">
        <span className="text-accent text-sm">
          {data.startDate} - {data.endDate}
        </span>
        <h4 className="text-xl">{data.title}</h4>
        <div className="flex items-center">
          <span className="text-accent pr-2 text-3xl">•</span>
          <p className="text-sm">{data.company}</p>
        </div>
      </div>
    </div>
  );
}

// src/app/components/resume/content-card/content-card.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-content-card',
  standalone: true,
  imports: [],
  templateUrl: './content-card.component.html',
  styleUrl: './content-card.component.scss'
})
export class ContentCardComponent {
  data = input.required<ResumeData>();
}

<div class="p-8 bg-secondary rounded-lg">
  <div class="flex flex-col gap-4">
    <span class="text-accent text-sm"
      >{{ data().startDate }} - {{ data().endDate }}</span
    >
    <h4 class="text-xl">{{ data().title }}</h4>
    <div class="flex items-center">
      <span class="text-accent pr-2 text-3xl">•</span>
      <p class="font-thin text-sm">{{ data().company }}</p>
    </div>
  </div>
</div>
