// src/app/components/resume/resume.component.ts
import { Component, inject, signal } from '@angular/core';
import { NgClass } from '@angular/common';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import {
  simpleTailwindcss,
  simpleAngular,
  simpleReact,
  simpleNodedotjs,
  simpleFlutter,
  simpleNextdotjs,
  simpleRedux,
  simpleAndroid,
} from '@ng-icons/simple-icons';

import { ResumeContentComponent } from './resume-content/resume-content.component';
import { ContentCardComponent } from './content-card/content-card.component';
import { ResumeService } from './resume.service';

@Component({
  selector: 'app-resume',
  standalone: true,
  imports: [
    NgClass,
    ResumeContentComponent,
    ContentCardComponent,
    NgIconComponent,
  ],
  providers: [
    provideIcons({
      simpleTailwindcss,
      simpleAngular,
      simpleReact,
      simpleNodedotjs,
      simpleFlutter,
      simpleNextdotjs,
      simpleRedux,
      simpleAndroid,
    }),
  ],
  templateUrl: './resume.component.html',
  styleUrl: './resume.component.scss',
})
export class ResumeComponent {
  activeMenu = signal(0);
  private resumeService = inject(ResumeService);

  resumeMenus = this.resumeService.resumeMenus;
  skills = this.resumeService.skills;
  educationData = this.resumeService.educationData;
  experienceData = this.resumeService.experienceData;

  onMenuClicked(menuIndex: number): void {
    this.activeMenu.set(menuIndex);
  }
}

<section class="container mt-12 lg:mt-24" id="resume">
  <h2
    class="text-3xl lg:text-4xl font-bold relative inline-block after:content-[''] after:absolute after:left-0 after:-bottom-3 after:w-1/2 after:h-1 after:bg-accent after:rounded-lg"
  >
    Resume
  </h2>
  <div class="flex flex-col lg:flex-row gap-12">
    <div class="lg:w-1/3">
      <p class="pt-6">
        Here is my experince, education, and skills that I have done. You can
        check it out.
      </p>

      <!-- Resume Menu -->
      <div class="flex flex-row lg:flex-col gap-4 mt-8 overflow-x-auto">
        @for (menu of resumeMenus; track menu.id) {
        <a
          class="py-2 rounded-lg cursor-pointer px-6 lg:px-0"
          [ngClass]="
            menu.id === activeMenu()
              ? 'bg-accent text-primary'
              : 'text-white bg-secondary'
          "
          (click)="activeMenu.set(menu.id)"
        >
          <p class="text-center text-sm lg:text-base">{{ menu.name }}</p>
        </a>
        }
      </div>
    </div>

    <!-- Menu content -->
    <div class="lg:w-2/3 lg:mt-6">
      @if (activeMenu() === 0) {
      <app-resume-content
        title="My Experience"
        description="Here is my experience that I have done."
      >
        <div class="grid lg:grid-cols-2 gap-6 mt-6 max-h-[500px] lg:max-h-96 overflow-y-scroll">
          @for (experience of experienceData; track $index) {
          <app-content-card [data]="experience"></app-content-card>
          }
        </div>
      </app-resume-content>
      } @else if (activeMenu() === 1) {
      <app-resume-content
        title="My Education"
        description="Here is my education that I have done."
      >
        <div class="grid lg:grid-cols-2 gap-6 mt-6 max-h-[500px] lg:max-h-96 overflow-y-scroll">
          @for (education of educationData; track $index) {
          <app-content-card [data]="education"></app-content-card>
          }
        </div>
      </app-resume-content>
      } @else if (activeMenu() === 2) {
      <div class="min-h-[500px]">
        <h3 class="text-2xl lg:text-3xl">My Skills</h3>
        <p class="pt-4">Here are the skills I have mastered.</p>
        <ul
          class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 lg:gap-6 mt-6"
        >
          @for (skill of skills; track $index) {
          <li class="flex items-center gap-2">
            <div
              class="w-full h-36 bg-secondary rounded-lg flex justify-center items-center group cursor-pointer"
            >
              <ng-icon
                [name]="skill.icon"
                class="text-6xl group-hover:text-accent transition-all duration-300"
              ></ng-icon>
            </div>
          </li>
          }
        </ul>
      </div>
      }
    </div>
  </div>
</section>

// src/components/resume/index.tsx
'use client'

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import ResumeContent from './ResumeContent';
import ContentCard from './ContentCard';
import { educationData, experienceData, resumeMenus, skills } from '@/src/data/resume';

export default function Resume() {
  const [activeMenu, setActiveMenu] = useState<number>(0);

  return (
    <section className="container mt-12 lg:mt-24" id="resume">
      <h2 className="text-3xl lg:text-4xl font-bold relative inline-block after:content-[''] after:absolute after:left-0 after:-bottom-3 after:w-1/2 after:h-1 after:bg-accent after:rounded-lg">
        Resume
      </h2>

      <div className="flex flex-col lg:flex-row gap-12 mt-6">
        <motion.div
          initial={{ opacity: 0, x: -40 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, ease: 'easeOut' }}
          viewport={{ once: true }}
          className="lg:w-1/3"
        >
          <p className="pt-6">
            Here is my experience, education, and skills that I have done. You
            can check it out.
          </p>

          <div className="flex flex-row lg:flex-col gap-4 mt-8 overflow-x-auto">
            {resumeMenus.map((menu) => (
              <button
                key={menu.id}
                onClick={() => setActiveMenu(menu.id)}
                className={`py-2 rounded-lg cursor-pointer px-6 lg:px-0 ${
                  activeMenu === menu.id
                    ? 'bg-accent text-primary'
                    : 'text-white bg-secondary'
                }`}
              >
                <p className="text-center text-sm lg:text-base">{menu.name}</p>
              </button>
            ))}
          </div>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, x: 40 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, ease: 'easeOut', delay: 0.2 }}
          viewport={{ once: true }}
          className="lg:w-2/3 lg:mt-6"
        >
          <AnimatePresence mode="wait">
            {activeMenu === 0 && (
              <motion.div
                key="experience"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                transition={{ duration: 0.4 }}
              >
                <ResumeContent
                  title="My Experience"
                  description="Here is my experience that I have done."
                >
                  <div className="grid lg:grid-cols-2 gap-6 mt-6 max-h-[500px] lg:max-h-96 overflow-y-scroll">
                    {experienceData.map((item, index) => (
                      <ContentCard key={index} data={item} />
                    ))}
                  </div>
                </ResumeContent>
              </motion.div>
            )}

            {activeMenu === 1 && (
              <motion.div
                key="education"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                transition={{ duration: 0.4 }}
              >
                <ResumeContent
                  title="My Education"
                  description="Here is my education that I have done."
                >
                  <div className="grid lg:grid-cols-2 gap-6 mt-6 max-h-[500px] lg:max-h-96 overflow-y-scroll">
                    {educationData.map((item, index) => (
                      <ContentCard key={index} data={item} />
                    ))}
                  </div>
                </ResumeContent>
              </motion.div>
            )}

            {activeMenu === 2 && (
              <motion.div
                key="skills"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                transition={{ duration: 0.4 }}
              >
                <div className="min-h-[500px]">
                  <h3 className="text-2xl lg:text-3xl">My Skills</h3>
                  <p className="pt-4">Here are the skills I have mastered.</p>
                  <ul className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 lg:gap-6 mt-6">
                    {skills.map((skill, index) => (
                      <li key={index} className="flex items-center gap-2">
                        <div className="w-full h-36 bg-secondary rounded-lg flex justify-center items-center group cursor-pointer">
                          <skill.icon className="text-6xl group-hover:text-accent transition-all duration-300" />
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      </div>
    </section>
  );
}
