// src/app/components/contact/contact.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { SocialComponent } from '../home/social/social.component';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [SocialComponent, ReactiveFormsModule],
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.scss',
})
export class ContactComponent {
  private formBuilder = inject(FormBuilder);
  contactForm = this.formBuilder.group({
    name: ['', Validators.required],
    email: ['', Validators.required],
    message: ['', Validators.required],
  });

  onSubmit() {
    if (this.contactForm.valid) {
      const { name, email, message } = this.contactForm.value;
      const mailtoURL = `mailto:ihsan.inh@gmail.com?subject=Message from ${name} - ${email}&body=${message}`;
      window.location.href = mailtoURL;

      this.contactForm.reset();
    }
  }
}

<section class="container mt-12 lg:mt-24" id="contact">
  <h2
    class="text-3xl lg:text-4xl font-bold relative inline-block after:content-[''] after:absolute after:left-0 after:-bottom-3 after:w-1/2 after:h-1 after:bg-accent after:rounded-lg"
  >
    Contact
  </h2>
  <div class="flex flex-col lg:flex-row space-between mt-6">
    <div class="w-full lg:w-1/2 flex flex-col gap-6">
      <p class="leading-9">
        Have an idea you'd like me to work on? Feel free to reach out! reach
        out! <br />
        You can contact me through the form or connect with me on
        social media below.
      </p>
      <app-social
        containerClass="flex gap-6"
        iconStyle="w-9 h-9 border border-accent rounded-full flex justify-center 
        items-center text-accent text-base hover:bg-accent 
        hover:text-primary hover:transition-all duration-500"
      >
      </app-social>
    </div>

    <form
      class="w-full lg:w-1/2 flex flex-col gap-6 mt-6 lg:mt-0"
      [formGroup]="contactForm"
      (ngSubmit)="onSubmit()"
    >
      <div class="flex flex-col gap-1">
        <label for="name">Your Name</label>
        <input
          type="text"
          placeholder="Enter your name"
          class="bg-secondary rounded-xl py-4 px-6"
          formControlName="name"
        />
      </div>
      <div class="flex flex-col gap-1">
        <label for="email">Your Email</label>
        <input
          id="email"
          type="text"
          placeholder="Enter your email"
          class="bg-secondary rounded-xl py-4 px-6"
          formControlName="email"
        />
      </div>
      <div class="flex flex-col gap-1">
        <label for="message">Write your message here</label>
        <textarea
          rows="6"
          type="text"
          placeholder="Enter your message"
          class="bg-secondary rounded-xl py-4 px-6 resize-none"
          formControlName="message"
        ></textarea>
      </div>

      <button
        type="submit"
        class="bg-accent px-6 py-1.5 text-primary rounded-full w-min disabled:cursor-not-allowed"
        [disabled]="contactForm.invalid"
      >
        Submit
      </button>
    </form>
  </div>
</section>

// src/components/contact/index.tsx
'use client';

import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import Social from './Social';
import { motion } from 'framer-motion';

const contactSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  email: z.string().min(1, 'Email is required').email('Invalid email format'),
  message: z.string().min(1, 'Message is required').max(500, 'Message cannot exceed 500 characters'),
});

type ContactFormData = z.infer<typeof contactSchema>;

export default function Contact() {
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isValid },
  } = useForm<ContactFormData>({
    resolver: zodResolver(contactSchema),
    mode: 'onChange',
  });

  const onSubmit = (data: ContactFormData) => {
    const { name, email, message } = data;
    const mailtoURL = `mailto:ihsan.inh@gmail.com?subject=Message from ${name} - ${email}&body=${message}`;
    window.location.href = mailtoURL;
    reset();
  };

  return (
    <section className="container mt-12 lg:mt-24" id="contact">
      <h2 className="text-3xl lg:text-4xl font-bold relative inline-block after:content-[''] after:absolute after:left-0 after:-bottom-3 after:w-1/2 after:h-1 after:bg-accent after:rounded-lg">
        Contact
      </h2>

      <div className="flex flex-col lg:flex-row space-between mt-6">
        <motion.div
          initial={{ opacity: 0, x: -40 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, ease: 'easeOut' }}
          viewport={{ once: true }}
          className="w-full lg:w-1/2 flex flex-col gap-6"
        >
          <p className="leading-9">
            Have an idea you&apos;d like me to work on? Feel free to reach out! <br />
            You can contact me through the form or connect with me on social media below.
          </p>
          <Social
            containerClass="flex gap-6"
            iconStyle="w-9 h-9 border border-accent rounded-full flex justify-center items-center text-accent text-base hover:bg-accent hover:text-primary transition-all duration-500"
          />
        </motion.div>

        <motion.form
          initial={{ opacity: 0, x: 40 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, ease: 'easeOut', delay: 0.2 }}
          viewport={{ once: true }}
          className="w-full lg:w-1/2 flex flex-col gap-6 mt-6 lg:mt-0"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="flex flex-col gap-1">
            <label htmlFor="name">Your Name</label>
            <input
              type="text"
              placeholder="Enter your name"
              className="bg-secondary rounded-xl py-4 px-6"
              {...register('name')}
            />
            {errors.name && <span className="text-red-500 text-sm">{errors.name.message}</span>}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="email">Your Email</label>
            <input
              type="text"
              placeholder="Enter your email"
              className="bg-secondary rounded-xl py-4 px-6"
              {...register('email')}
            />
            {errors.email && <span className="text-red-500 text-sm">{errors.email.message}</span>}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="message">Write your message here</label>
            <textarea
              rows={6}
              placeholder="Enter your message"
              className="bg-secondary rounded-xl py-4 px-6 resize-none"
              {...register('message')}
            />
            {errors.message && (
              <span className="text-red-500 text-sm">{errors.message.message}</span>
            )}
          </div>

          <button
            type="submit"
            className="cursor-pointer bg-accent px-6 py-2 text-primary rounded-full shadow-md transform transition-all duration-300 hover:scale-105 hover:shadow-lg hover:shadow-accent/50 w-min disabled:cursor-not-allowed"
            disabled={!isValid}
          >
            Submit
          </button>
        </motion.form>
      </div>
    </section>
  );
}
