// src/features/portfolio/components/resume/index.tsx
"use client";

import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";

import {
  certifications,
  educationData,
  experienceData,
  resumeMenus,
} from "@/src/features/portfolio/data/resume";
import ScrollReveal from "@/src/shared/components/ScrollReveal";

import CertificationsList from "./CertificationsList";
import ResumeContent from "./ResumeContent";
import Timeline from "./Timeline";

export default function Resume() {
  const [activeMenu, setActiveMenu] = useState<number>(0);

  return (
    <section className="container mt-12 lg:mt-24" id="resume">
      <ScrollReveal animation="slide-up">
        <h2 className="section-title">Resume</h2>
      </ScrollReveal>

      <div className="flex flex-col lg:flex-row gap-8 lg:gap-12 mt-6">
        {/* Left sidebar */}
        <ScrollReveal animation="slide-right" className="lg:w-1/3">
          <p className="pt-4 text-slate-700 dark:text-white/70">
            Here are my experiences, educations, and skills. Feel free to check
            them out.
          </p>

          {/* Clean Tab Navigation */}
          <div className="flex flex-row lg:flex-col gap-2 mt-6 overflow-x-auto pb-2 lg:pb-0">
            {resumeMenus.map((menu) => {
              const isActive = activeMenu === menu.id;
              return (
                <button
                  key={menu.id}
                  onClick={() => setActiveMenu(menu.id)}
                  className={`
                    relative py-3 px-5 rounded-xl cursor-pointer text-sm lg:text-base font-medium 
                    transition-all duration-300 whitespace-nowrap border
                    ${
                      isActive
                        ? "text-white shadow-lg border-transparent"
                        : "text-slate-700 dark:text-white/80 bg-white dark:bg-white/5 border-slate-200 dark:border-white/10 hover:border-[rgb(var(--accent)/0.3)]"
                    }
                  `}
                >
                  {/* Background for active state */}
                  <span
                    className={`
                      absolute inset-0 rounded-xl transition-all duration-300
                      ${
                        isActive
                          ? "bg-gradient-to-r from-[rgb(var(--accent))] to-[rgb(var(--accent-secondary))] opacity-100"
                          : "opacity-0"
                      }
                    `}
                  />

                  <span className="relative z-10">{menu.name}</span>
                </button>
              );
            })}
          </div>
        </ScrollReveal>

        {/* Right content */}
        <div className="lg:w-2/3">
          <AnimatePresence mode="wait">
            {activeMenu === 0 && (
              <motion.div
                key="experience"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3, ease: "easeOut" }}
              >
                <ResumeContent
                  title="My Experiences"
                  description="Here is an overview of the roles and responsibilities I've held."
                >
                  <Timeline items={experienceData} className="mt-6" />
                </ResumeContent>
              </motion.div>
            )}

            {activeMenu === 1 && (
              <motion.div
                key="education"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3, ease: "easeOut" }}
              >
                <ResumeContent
                  title="My Educations"
                  description="Here is an overview of my academic background."
                >
                  <Timeline items={educationData} className="mt-6" />
                </ResumeContent>
              </motion.div>
            )}

            {activeMenu === 2 && (
              <motion.div
                key="certifications"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3, ease: "easeOut" }}
              >
                <ResumeContent
                  title="My Certifications"
                  description="Industry-recognized certificates and training I've completed."
                >
                  <CertificationsList items={certifications} className="mt-6" />
                </ResumeContent>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </section>
  );
}

// src/app/components/resume/resume.component.ts
import { Component, inject, signal } from '@angular/core';
import { NgClass } from '@angular/common';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import {
  simpleTailwindcss,
  simpleAngular,
  simpleReact,
  simpleNodedotjs,
  simpleFlutter,
  simpleNextdotjs,
  simpleRedux,
  simpleAndroid,
} from '@ng-icons/simple-icons';

import { ResumeContentComponent } from './resume-content/resume-content.component';
import { ContentCardComponent } from './content-card/content-card.component';
import { ResumeService } from './resume.service';

@Component({
  selector: 'app-resume',
  standalone: true,
  imports: [
    NgClass,
    ResumeContentComponent,
    ContentCardComponent,
    NgIconComponent,
  ],
  providers: [
    provideIcons({
      simpleTailwindcss,
      simpleAngular,
      simpleReact,
      simpleNodedotjs,
      simpleFlutter,
      simpleNextdotjs,
      simpleRedux,
      simpleAndroid,
    }),
  ],
  templateUrl: './resume.component.html',
  styleUrl: './resume.component.scss',
})
export class ResumeComponent {
  activeMenu = signal(0);
  private resumeService = inject(ResumeService);

  resumeMenus = this.resumeService.resumeMenus;
  skills = this.resumeService.skills;
  educationData = this.resumeService.educationData;
  experienceData = this.resumeService.experienceData;

  onMenuClicked(menuIndex: number): void {
    this.activeMenu.set(menuIndex);
  }
}

<section class="container mt-12 lg:mt-24" id="resume">
  <h2
    class="text-3xl lg:text-4xl font-bold relative inline-block after:content-[''] after:absolute after:left-0 after:-bottom-3 after:w-1/2 after:h-1 after:bg-accent after:rounded-lg"
  >
    Resume
  </h2>
  <div class="flex flex-col lg:flex-row gap-12">
    <div class="lg:w-1/3">
      <p class="pt-6">
        Here is my experince, education, and skills that I have done. You can
        check it out.
      </p>

      <!-- Resume Menu -->
      <div class="flex flex-row lg:flex-col gap-4 mt-8 overflow-x-auto">
        @for (menu of resumeMenus; track menu.id) {
        <a
          class="py-2 rounded-lg cursor-pointer px-6 lg:px-0"
          [ngClass]="
            menu.id === activeMenu()
              ? 'bg-accent text-primary'
              : 'text-white bg-secondary'
          "
          (click)="activeMenu.set(menu.id)"
        >
          <p class="text-center text-sm lg:text-base">{{ menu.name }}</p>
        </a>
        }
      </div>
    </div>

    <!-- Menu content -->
    <div class="lg:w-2/3 lg:mt-6">
      @if (activeMenu() === 0) {
      <app-resume-content
        title="My Experience"
        description="Here is my experience that I have done."
      >
        <div class="grid lg:grid-cols-2 gap-6 mt-6 max-h-[500px] lg:max-h-96 overflow-y-scroll">
          @for (experience of experienceData; track $index) {
          <app-content-card [data]="experience"></app-content-card>
          }
        </div>
      </app-resume-content>
      } @else if (activeMenu() === 1) {
      <app-resume-content
        title="My Education"
        description="Here is my education that I have done."
      >
        <div class="grid lg:grid-cols-2 gap-6 mt-6 max-h-[500px] lg:max-h-96 overflow-y-scroll">
          @for (education of educationData; track $index) {
          <app-content-card [data]="education"></app-content-card>
          }
        </div>
      </app-resume-content>
      } @else if (activeMenu() === 2) {
      <div class="min-h-[500px]">
        <h3 class="text-2xl lg:text-3xl">My Skills</h3>
        <p class="pt-4">Here are the skills I have mastered.</p>
        <ul
          class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 lg:gap-6 mt-6"
        >
          @for (skill of skills; track $index) {
          <li class="flex items-center gap-2">
            <div
              class="w-full h-36 bg-secondary rounded-lg flex justify-center items-center group cursor-pointer"
            >
              <ng-icon
                [name]="skill.icon"
                class="text-6xl group-hover:text-accent transition-all duration-300"
              ></ng-icon>
            </div>
          </li>
          }
        </ul>
      </div>
      }
    </div>
  </div>
</section>
